### ISSUE TITLE
Need to update dependencies; 

### ISSUE THREAD

**Issue by LassiterJ** [alexgurr/react-coding-challenges#11]
None of the challenges work without fixing dependency issues. 

For example, this error happens when I yarn start the dark-mode with skip preflight check in a .env
"
./src/styles/_main.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/styles/_main.scss)
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (88)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1"

**Comment by alexgurr** [comment]
Hi Lassiter. This is probably because you're on an Apple silicon mac which doesn't support some of the older versions of libraries. I'll take a look at updating all the dependencies.

**Comment by grayson073** [comment]
Opened https://github.com/alexgurr/react-coding-challenges/pull/13

**Comment by alexgurr** [comment]
@LassiterJ can you confirm this resolves the above issues? If so, happy to merge this PR.

**Comment by grayson073** [comment]
Should have mentioned that prior to upgrading I ran into the same error as @LassiterJ for each exercise and`npm rebuild node-sass` for each directory was the main quick-fix (though it takes some time for the rebuild to complete after each run). Anyways just confirming error was reproduced on my end as well.
