### ISSUE TITLE
Dependencies do not install

### ISSUE THREAD

**Issue by sonu27** [alexgurr/react-coding-challenges#14]
## Expected behaviour
Dependencies should install

## Actual behaviour
Dependencies do not resolve after `npm install`
Error message:
```
rocket-ship git:(master) npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @babel/core@7.12.3
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.12.3" from react-scripts@4.0.3
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"^4.0.3" from the root project
npm ERR!   @babel/core@"^7.12.3" from @svgr/webpack@5.5.0
npm ERR!   node_modules/@svgr/webpack
npm ERR!     @svgr/webpack@"5.5.0" from react-scripts@4.0.3
npm ERR!     node_modules/react-scripts
npm ERR!       react-scripts@"^4.0.3" from the root project
npm ERR!   9 more (babel-jest, babel-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.13.12
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.13.12" from @babel/preset-env@7.13.12
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.12.1" from @svgr/webpack@5.5.0
npm ERR!     node_modules/@svgr/webpack
npm ERR!       @svgr/webpack@"5.5.0" from react-scripts@4.0.3
npm ERR!       node_modules/react-scripts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## I'm seeing this behaviour on
node: `v15.12.0`
npm: `v7.7.1`

- [X] Desktop
- [ ] Mobile
- [ ] N/A

## I'm not a dummy, so I've checked these
- [X] I've run `yarn` / `npm install`.
- [X] I'm using an up to date nodeJS version.
- [X] My issue doesn't already exist
- [X] I'm not on an M1 Mac, or if I am, I googled the issue first.

## So how can we reproduce this?
`npm i`

**Comment by hellosurbhi** [comment]
Hey! This seems to be a persistent issue with npm 7. Their team documented it [https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major](here). 

In order to get around this, you need to use this command instead 
`npm install --legacy-peer-deps`
Hope this helps!

**Comment by alexgurr** [comment]
Yarn is so much quicker and better these days. Have a try installing and using it instead.

**Comment by alexgurr** [comment]
Closing this as solutions have been posted. If you continue to have problems, feel free to reopen.

**Comment by sonu27** [comment]
@alexgurr ah, I thought npm had caught up with yarn
