### ISSUE TITLE
Solutions page throws a CORS error

### ISSUE THREAD

**Issue by cricklet** [alexgurr/react-coding-challenges#29]
Hi!

## Expected behaviour

I'd expect logins to succeed on https://www.solutions.alexgurr.com/

## Actual behaviour

<img width="938" alt="Screen Shot 2021-12-31 at 3 50 57 PM" src="https://user-images.githubusercontent.com/659021/147841258-c3dc3be9-b37d-431e-aeec-35fae90ba36c.png">
<img width="547" alt="Screen Shot 2021-12-31 at 3 51 28 PM" src="https://user-images.githubusercontent.com/659021/147841259-af5d3c5f-9bc5-423d-8c67-fc6f5d16d86b.png">

Seeing this on Chrome on OSX.

**Comment by alexgurr** [comment]
This happens for about 12 hours a month when the heroku free dyno hours are maxed! All fine now.

**Comment by sailor95** [comment]
It seems to happen again, I've tested several times with each interval longer than 24hr yet still couldn't get in.
