### ISSUE TITLE
Access to solutions repo

### ISSUE THREAD

**Issue by thebspin** [alexgurr/react-coding-challenges#5]
Hi i already asked this on Twitter but maybe you missed it or don't look that much in Twitter (can't blame you, neither do i) but i liked to have access to the solutions repo.
Thanks in advance!

**Comment by LassiterJ** [comment]
Hi! Thank you for providing this repo @alexgurr ! I also am requesting access to your repo of answers.

**Comment by alexgurr** [comment]
Hi Jon. I've invited you.

**Comment by lcarro-lclk** [comment]
Hi Alex! Thank you for your work @alexgurr . Can you invite me to your repo of answers?

**Comment by alexgurr** [comment]
Hi Clement. Please read the solutions section of the readme - https://github.com/alexgurr/react-coding-challenges#have-you-got-the-solutions
