### ISSUE TITLE
CORS error on solution site

### ISSUE THREAD

**Issue by sailor95** [alexgurr/react-coding-challenges#74]
## Expected behaviour

Expect logins to succeed on https://www.solutions.alexgurr.com/.

## Actual behaviour

Access been blocked just like what #29 stated, I've tested several times with each interval longer than 24hr to bypass the [heroku issue](https://github.com/alexgurr/react-coding-challenges/issues/29#issuecomment-1006200836) yet still couldn't get in.

![image](https://user-images.githubusercontent.com/26215730/209557296-671073b5-a69e-4751-a828-7d5b14f75a86.png)

## I'm seeing this behaviour on

- [x] Desktop
- [ ] Mobile
- [ ] N/A

## OS

Windows, Chrome

**Comment by alexgurr** [comment]
Fixed 👍
